### ISSUE TITLE
Documentation / collaboration.

### ISSUE THREAD

**Issue by jordwalke** [dzhou121/envim#1]
Hi @dzhou121 would you be able to explain a bit about this project. As someone on the React team, and as a vim fanatic, it's very interesting to me. Does this require your neovim patch that externalizes the UI of neovim?

**Comment by dzhou121** [comment]
Hi @jordwalke Thank you for your interest. 

Yes, to run this project, you would need nvim built with that PR, as explained in the newly added README. This project is a bit messy in terms of code at the moment. So please feel free to drop a line if you can't get it working.

**Comment by mhartington** [comment]
Hey @dzhou121, very interested in this as well. Took a bit, but was missing all your deps. Once adding those and cloning your fork of nvim with your PR, I got things running (yay). But some errors came up

<img width="1680" alt="screen shot 2016-12-06 at 8 27 26 pm" src="https://cloud.githubusercontent.com/assets/2835826/20951223/90cfeee2-bbf2-11e6-8008-767614746b4f.png">
 

Any idea?

**Comment by dzhou121** [comment]
Hi @mhartington The error looks like it can't find the nvim binary. Are you providing the right path?

**Comment by mhartington** [comment]
I'm modifying this path

https://github.com/dzhou121/envim/blob/master/index.js#L180

**Comment by dzhou121** [comment]
Are you able to run the nvim binary directly from terminal?

**Comment by mhartington** [comment]
I'll have to look into that, seems to be the cause of the issue. 
I can run your fork, but no UI is drawn

**Comment by dzhou121** [comment]
Just to remind that it's on external-ui branch rather than master.

**Comment by mhartington** [comment]
yep

```
rm -r build
make clean
make CMAKE_BUILD_TYPE=Release
```

**Comment by dzhou121** [comment]
You might want to pull the latest on both repos. They might not in sync in terms of features I was working on.

**Comment by gilligan** [comment]
@dzhou121 could you add some more info on how to get things up and running? First of all not all dependencies are there:

* babel-preset-es2015
* react

With both of those installed I try to run `node bootstrap.js` which then fails:

```
/home/gilligan/Development/envim/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /home/gilligan/Development/envim/main.js: Unknown option: base.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.
    at Logger.error (/home/gilligan/Development/envim/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/home/gilligan/Development/envim/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:20)
    at OptionManager.init (/home/gilligan/Development/envim/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/gilligan/Development/envim/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/gilligan/Development/envim/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/gilligan/Development/envim/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.transformFileSync (/home/gilligan/Development/envim/node_modules/babel-core/lib/api/node.js:138:10)
    at compile (/home/gilligan/Development/envim/node_modules/babel-register/lib/node.js:118:20)
    at loader (/home/gilligan/Development/envim/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/gilligan/Development/envim/node_modules/babel-register/lib/node.js:154:7)

```

**Comment by gilligan** [comment]
sorry, i have to run this through electron I suppose..

**Comment by vdeurzen** [comment]
@dzhou121  I too am having some difficulty getting this to show the UI. Same error as @gilligan. Any documentation on how to set this up?

**Comment by dzhou121** [comment]
I've updated dependencies in package.json now. You can pull the latest and run:

```
$> npm install
$> electron .
```

**Comment by acornejo** [comment]
This project is great!!!! I hope your PR gets merged soon.
